import numpy as np
print(np.zeros((3,4)))
print("........................")
print(np.ones((3,4)))
print("........................")
print(np.arange(1,5))
print(np.arange(1,5,2))
print("........................")
print(np.linspace(1,5,10))
print(np.linspace(1,5,5))
print("........................")
print("........................")
a = (np.array([[1,2],[3,4],[5,6]]))
print(a.shape)
print(a.reshape(2,3))
print(a.reshape(1,6))
print(a.ravel())
print("........................")
print(a)
print(a.min())
print(a.max())
print(a.sum())
print("........................")

print("........................")

print("........................")
print("........................")
print(a.sum(axis=0))
print(a.sum(axis=1))